/**
 * layout.js
 */

import "./globals.css";
import { Inter } from "next/font/google";

import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth/next";

import Providers from "@/components/provider";
import Preline from "@/components/preline";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/created/navigation/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <Preline />
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <NavBar />
            <main className="flex w-full flex-1 flex-col overflow-hidden bg-background">
              {children}
            </main>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
