/**
 * layout.js
 */

import './globals.css'
import { Inter } from 'next/font/google'

import { authOptions } from './api/auth/[...nextauth]/route'
import { getServerSession } from "next-auth/next"


import Providers from '@/components/provider'
import Preline from '@/components/preline'
import { ThemeProvider } from '@/components/theme-provider'
import { MainNav } from '@/components/main-nav'
import TeamSwitcher from '@/components/team-switcher'
import { Search } from '@/components/search'
import { UserNav } from '@/components/user-nav'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)


  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <>
            <div className="border-b">
              <div className="flex items-center h-16 px-4">
                <TeamSwitcher />
                <MainNav className="mx-6" />
                <div className="flex items-center ml-auto space-x-4">
                  <Search />
                  <UserNav />
                </div>
              </div>
            </div>
          </>
          <Preline />
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  )
}
